### ISSUE TITLE
ModuleNotFoundError: No module named 'pyA20'

### ISSUE THREAD

**Issue by eduhza** [OLIMEX/BB-ADS1220#1]
Hi, I've bought an ADS1220 and trying to run it in Python.
However I get an error when I try to install pyA20.

The following message appers with pip installation:

> pip3 install --upgrade pyA20
Collecting pyA20
  Using cached pyA20-0.2.1.tar.gz
Installing collected packages: pyA20
  Running setup.py install for pyA20 ... error
    Complete output from command c:\users\eduhz\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\eduhz\\AppData\\Local\\Temp\\pip-build-it42lil_\\pyA20\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\eduhz\AppData\Local\Temp\pip-9rkqx1in-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\pyA20
    copying pyA20\__init__.py -> build\lib.win32-3.6\pyA20
    creating build\lib.win32-3.6\pyA20\gpio
    copying pyA20\gpio\__init__.py -> build\lib.win32-3.6\pyA20\gpio
    running build_ext
    error: [Errno 2] No such file or directory: '/proc/cpuinfo'

    ----------------------------------------
Command "c:\users\eduhz\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\eduhz\\AppData\\Local\\Temp\\pip-build-it42lil_\\pyA20\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\eduhz\AppData\Local\Temp\pip-9rkqx1in-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\eduhz\AppData\Local\Temp\pip-build-it42lil_\pyA20\

>

**Comment by DanKoloff** [comment]
The library can't find directory '/proc/cpuinfo'. This demo was probably made with relative file paths and tested with our single-board computers with A20 chip inside. So if the directory structure at your side is different you need to set absolute paths (or edit the relative paths to match your machine).
